"""'create users and dates'

Revision ID: 41430de44f43
Revises: 
Create Date: 2026-10-02 00:10:29.149450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41430de44f43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Europe/Moscow', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('place', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('planned', 'done', 'cancelled', name='date_status'), server_default='planned', nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('remind_two_day_before_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remind_day_before_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remind_hours_before_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name='ck_dates_ends_after_starts'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_dates_rating_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dates_created_by'), 'dates', ['created_by'], unique=False)
    op.create_index(op.f('ix_dates_starts_at'), 'dates', ['starts_at'], unique=False)
    op.create_index(op.f('ix_dates_status'), 'dates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dates_status'), table_name='dates')
    op.drop_index(op.f('ix_dates_starts_at'), table_name='dates')
    op.drop_index(op.f('ix_dates_created_by'), table_name='dates')
    op.drop_table('dates')
    op.drop_table('users')
    # ### end Alembic commands ###
