"""date reviews and review photos

Revision ID: b3a3f3aab717
Revises: 75c781494181
Create Date: 2026-10-08 01:59:00.509806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a3f3aab717'
down_revision: Union[str, Sequence[str], None] = '75c781494181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('liked', sa.Text(), nullable=True),
    sa.Column('disliked', sa.Text(), nullable=True),
    sa.Column('food', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_date_reviews_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['date_id'], ['dates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_id', 'author_id', name='uq_date_reviews_date_author')
    )
    op.create_index(op.f('ix_date_reviews_date_id'), 'date_reviews', ['date_id'], unique=False)
    op.create_table('date_review_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('tg_file_id', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position BETWEEN 0 AND 9', name='ck_date_review_photos_position_range'),
    sa.CheckConstraint('size > 0', name='ck_date_review_photos_size_positive'),
    sa.ForeignKeyConstraint(['review_id'], ['date_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('review_id', 'position', name='uq_date_review_photos_position')
    )
    op.drop_column('dates', 'rating')
    op.drop_column('dates', 'review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates', sa.Column('review', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dates', sa.Column('rating', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_table('date_review_photos')
    op.drop_index(op.f('ix_date_reviews_date_id'), table_name='date_reviews')
    op.drop_table('date_reviews')
    # ### end Alembic commands ###
